// scripts/integrations/angular/src/app/editor-types/editor-types.component.ts
/**
 * @license Copyright (c) 2003-2025, CKSource Holding sp. z o.o. All rights reserved.
 * For licensing, see LICENSE.md.
 */

import { Component } from '@angular/core';

@Component( {
	selector: 'app-editor-types',
	templateUrl: './editor-types.component.html'
} )
export class EditorTypesComponent {
	public editorData = `<p>This is a CKEditor 4 WYSIWYG editor instance created with Angular.</p>`;
	public editorConfig = {
		extraPlugins: 'sourcedialog'
	}
}

<h2>{{ type }} Editor</h2>

<p>
	To use the CKEditor 4 WYSIWYG editor component, create a new <code>&lt;ckeditor&gt;</code> tag. The initial data of the editor can be set with the <code>data</code> property.
</p>

<p>
	Three available editor types are <strong>classic editor</strong> (default one), <strong>divarea editor</strong> (an inline editor with a <a href="./fixedui.html">fixed UI</a>) and <strong>inline editor</strong> with a <a href="./floatingui.html">floating UI</a>.
</p>

<p>Use the select below to change the editor type.</p>

<ckeditor
	*ngIf="!inline && !divarea"
	[(data)]="editorData">
</ckeditor>

<ckeditor
	*ngIf="divarea"
	type="divarea"
	[(data)]="editorData">
</ckeditor>

<ckeditor
	*ngIf="inline"
	type="inline"
	[(data)]="editorData">
</ckeditor>

<div class="select-editor-type">
	<label for="editor-type">Choose editor type:</label>

	<select id="editor-type" class="editor-type" (change)="onChange($event.target.value)">
		<option value="classic">Classic Editor</option>
		<option value="divarea">Divarea Editor</option>
		<option value="inline">Inline Editor</option>
	</select>
</div>

// scripts/integrations/react/EditorTypes.jsx
import React from 'react';
import { CKEditor } from 'ckeditor4-react';

const initData = <p>This is a CKEditor 4 WYSIWYG editor instance created by ️⚛️ React.</p>;
const editorConfig = {
	extraPlugins: 'sourcedialog'
};

const EditorTypes = () => (
	<div>
		<h2>Classic WYSIWYG editor</h2>
		<p>
			To use the CKEditor 4 <a href="./classic.html">classic editor</a> in React, create a new <code>&lt;CKEditor /&gt;</code> component. The initial data of the editor can be set with the <code>initData</code> property.
		</p>
		<CKEditor initData={initData} />
		<h2>Inline WYSIWYG editor</h2>
		<p>
			To use the CKEditor 4 <a href="./inline.html">inline editor</a> in React, set the <code>type</code> property of <code>&lt;CKEditor /&gt;</code> to <code>inline</code>.
		</p>
		<CKEditor type="inline" initData={initData} config={editorConfig} />
	</div>
);

export default EditorTypes;
